name: build

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository code
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          submodules: recursive  # 初始化和更新子模块

      # Build and Compile Code Directly Using the Custom Docker Image
      - name: Build in Docker Container
        run: |
          docker run --rm \
          -v ${{ github.workspace }}:/workspace \
          -w /workspace \
          zzjc1234/logicfactory_als \
          bash -c "
          mkdir -p build && cd build && \
          cmake -G Ninja .. && \
          ninja"

