name: build

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Compile Latest Code in Docker
        run: |
          docker run --rm \
          -v ${{ github.workspace }}:/workspace \
          zzjc1234/logicfactory_als:latest bash -c "
          cd /workspace && \
          git submodule update --init --recursive && \
          mkdir -p build && cd build && \
          cmake -G Ninja .. && \
          ninja"

