name: build

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code and Initialize Submodules
        uses: actions/checkout@v3
        with:
          submodules: recursive   # 确保子模块递归加载
          persist-credentials: true  # 保留 .git 文件夹

      - name: Compile Latest Code in Docker
        run: |
          docker run --rm \
            -e GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }} \
            -v ${{ github.workspace }}:/workspace \
            zzjc1234/logicfactory_als:latest bash -c "
            cd /workspace && \
            git config --global --add safe.directory /workspace && \
            git submodule update --init --recursive && \
            mkdir -p build && cd build && \
            cmake -G Ninja .. && \
            ninja"

