name: build

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true

      - name: Compile Latest Code in Docker
        run: |
          docker run --rm \
          -v ${{ github.workspace }}:/workspace \
          zzjc1234/logicfactory_als:latest bash -c "
          cd /workspace && \
          mkdir -p build && cd build && \
          cmake -G Ninja .. && \
          ninja"

